name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the pistols image
      run: docker build . --file pistols-dockerfile.yml --tag pistols:1.0
    - name: Push to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: u/akacodemonkey/pistols:1.0
        tag_with_ref: true
    - name: Build purple image
      run: docker build . --file purple-dockerfile.yml --tag purple:1.0
    - name: Push to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: u/akacodemonkey/purple:1.0
        tag_with_ref: true
