name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build-Push Pistols to dockerhub
      uses: docker/build-push-action@v1
      with:
        context: .
        file: pistols-dockerfile.yml
        push: true
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: u/akacodemonkey/pistols:1.0
        tag_with_ref: true
    - name: Build-Push Purple to dockerhub
      uses: docker/build-push-action@v1
      with:
      with:
        context: .
        file: purple-dockerfile.yml
        push: true
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: u/akacodemonkey/pistols:1.0
        tag_with_ref: true
